CREATE DATABASE IF NOT EXISTS abe_cloud_disk;
USE abe_cloud_disk;

-- 1. User table: Stores user information and their ABE attributes
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    attributes TEXT, -- Store user attributes, such as "LEAD_ENGINEER,PROJECT_PHOENIX"
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 2. ABE System Parameter Table: Stores the global public key and master key (BLOB is used to store serialized mathematical elements)
CREATE TABLE IF NOT EXISTS system_keys (
    id INT PRIMARY KEY DEFAULT 1,
    params TEXT NOT NULL,        -- PairingParameters serialized
    g BLOB NOT NULL,             -- Element g (generator)
    pk_h BLOB NOT NULL,          -- Element h
    pk_egg_alpha BLOB NOT NULL,  -- Element egg_alpha
    msk_beta BLOB NOT NULL,      -- Element beta
    msk_alpha BLOB NOT NULL,     -- Element alpha
    CHECK (id = 1)               -- Ensure there is only one record
) ENGINE=InnoDB;

-- 3. User ABE Private Key Table: A component that stores generated personalized private keys
CREATE TABLE IF NOT EXISTS user_keys (
    user_id INT PRIMARY KEY,
    sk_d BLOB NOT NULL,          -- Element D
    sk_dr BLOB NOT NULL,         -- Element D_r
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 4. File metadata table: Stores basic file information and AES IV data transmitted from the front end.
CREATE TABLE IF NOT EXISTS files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner_id INT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL, -- The physical path of the encrypted file on the server
    aes_iv VARBINARY(16) NOT NULL,   -- AES IV generated by the front end
    policy TEXT NOT NULL,            -- Access policy description, such as "PROJECT_PHOENIX AND LEAD_ENGINEER"
    upload_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 5. File ABE Ciphertext Component Table: Stores AES keys protected by ABE.
CREATE TABLE IF NOT EXISTS file_abe_data (
    file_id INT PRIMARY KEY,
    encrypted_session_key BLOB NOT NULL, -- AES key bytes after ABE masking
    ct_c BLOB NOT NULL,                  -- Element C
    ct_c_prime BLOB NOT NULL,            -- Element C_prime
    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
) ENGINE=InnoDB;
